### ISSUE TITLE
use Text component

### ISSUE THREAD

**Issue by galeindor** [IradDoron/pitcholympics#121]
in ```/components/core/``` we have ```Text.tsx``` component which is meant to prevent code duplication where we write:
```
<p className="text-light-surface-onPrimary dark:text-dark-surface-onPrimary font-inter"> {*some text* } </p>
```

all around the project, 
this refactor is:
1. great way to improve maintainabillity of the project.
2. prevent code duplication on text which is usually consitant.
3. great way to see all the pages of the project and get to know it.

availlable for any questions neede , write me here if you're willing to work on that issue 😄

**Comment by deevarzariu** [comment]
Hey, I would like to take this one.

**Comment by deevarzariu** [comment]
Hmm, actually, I notice that not many places in this project have elements with both `text-light-surface-onPrimary` and `font-inter` classes. I think I'm going to back out of this one :D

**Comment by galeindor** [comment]
> Hmm, actually, I notice that not many places in this project have elements with both `text-light-surface-onPrimary` and `font-inter` classes. I think I'm going to back out of this one :D

therefore you may change the component to fit the need of the application,
we can have 2/3 variants of the component className so we can catch as much code duplications as possible from the project,
if you are willing to try this you may find alot of places where we can improve the app using this Component if built properly
