### ISSUE TITLE
Create a Chip core component

### ISSUE THREAD

**Issue by IradDoron** [IradDoron/pitcholympics#134]
Create a generic component similar to the Chip component from MUI: https://mui.com/material-ui/react-chip/

For a start just all a "label" prop.

**Comment by mahesh-gunjal** [comment]
@IradDoron Can you assign this to me as I would like to work on this.

**Comment by AyalaZisman** [comment]
@IradDoron please assign me

**Comment by IradDoron** [comment]
Create branch with the name feature/ayala-zisman/chip-component

**Comment by danirdd92** [comment]
תעביר את הטיקט עליי

**Comment by danirdd92** [comment]
#183

**Comment by danirdd92** [comment]
#184
